-- Uphold Group, starter job listings.
--
-- Optional. Run after schema.sql if you want the board to open with the same
-- roles the local store seeds, rather than empty. Safe to run twice: a row
-- whose id already exists is left alone.

insert into jobs (
  id, slug, title, positions, suburb, region, trade,
  employment_type, duration, note, posted, valid_through,
  summary, requirements
) values
  ('UG-2411', 'construction-labourers-alexandria-ug-2411', 'Construction labourers', 6, 'Alexandria', 'inner-west', 'labourers', 'Casual', 'ongoing', '6am start, Mon–Fri', '2026-09-01', '2026-12-01', 'Six construction labourers for an ongoing commercial site in Alexandria, five minutes from our office. Site clean-up, materials handling and trades assistance on a Monday to Friday roster with a 6am start. Ongoing work for the right people, this crew has been on the same site for four months.', ARRAY['Current SafeWork NSW White Card', 'Steel-cap boots and your own PPE (we supply hi-vis)', 'Reliable transport to Alexandria for a 6am start', 'Right to work in Australia']::text[]),
  ('UG-2417', 'hoist-operator-parramatta-ug-2417', 'Hoist operator', 1, 'Parramatta', 'parramatta-western-sydney', 'scaffolders-riggers', 'Casual', '9 months', 'Hoist ticket required', '2026-09-03', '2026-12-03', 'Materials hoist operator for a 32-level residential tower in Parramatta. Nine months of continuous work on an established crew, day shift, with the level cycle already running. This is a long, stable booking rather than a fill-in shift.', ARRAY['Current HM or HP high-risk work licence', 'SafeWork NSW White Card', 'Experience operating a materials hoist on a high-rise site', 'Two recent supervisor references']::text[]),
  ('UG-2421', 'formwork-carpenters-macquarie-park-ug-2421', 'Formwork carpenters', 4, 'Macquarie Park', 'north-shore-hills', 'carpenters-formwork', 'Contract', '6 months', 'Own tools, EBA site', '2026-09-05', '2026-12-05', 'Four formwork carpenters for a six-month contract engagement on a commercial base build in Macquarie Park. EBA site with a full crew already mobilised, working table forms through the structure. Own hand tools required; site supplies everything else.', ARRAY['Certificate III in Carpentry or recognised equivalent', 'SafeWork NSW White Card and working at heights', 'Table form experience on a commercial structure', 'Own hand tools and nail gun']::text[]),
  ('UG-2424', 'traffic-controllers-leppington-ug-2424', 'Traffic controllers', 3, 'Leppington', 'south-west-liverpool', 'traffic-control', 'Casual', '4 months', 'TCT required, some night work', '2026-09-06', '2026-12-06', 'Three traffic controllers for a staged subdivision in Leppington. Mostly day shift with occasional night works for service connections. Four months of steady work for controllers who live in the South West corridor.', ARRAY['Current NSW Traffic Controller (TCT) accreditation', 'SafeWork NSW White Card', 'Driver licence and own transport', 'Availability for occasional night shifts']::text[]),
  ('UG-2428', 'excavator-operator-marsden-park-ug-2428', 'Excavator operator', 2, 'Marsden Park', 'parramatta-western-sydney', 'plant-operators', 'Casual', 'ongoing', '20–30t, VOC on arrival', '2026-09-07', '2026-12-07', 'Two excavator operators for bulk earthworks on a subdivision package at Marsden Park. Machines are 20 to 30 tonne; a verification of competency is completed on arrival. Ongoing work with a crew that has been on the package since the start.', ARRAY['Demonstrated experience on 20–30t excavators', 'SafeWork NSW White Card', 'Dogging (DG) ticket advantageous if lifting with the machine', 'Own transport to Marsden Park for a 6:30am start']::text[]),
  ('UG-2430', 'forklift-operators-eastern-creek-ug-2430', 'Forklift operators', 4, 'Eastern Creek', 'parramatta-western-sydney', 'warehouse-logistics', 'Casual', '3 months', 'Afternoon shift, LF licence', '2026-09-08', '2026-12-08', 'Four forklift operators for an afternoon shift at a distribution centre in Eastern Creek. Three-month peak engagement with a strong chance of ongoing work for operators who stick. Counterbalance and reach experience both useful.', ARRAY['Current LF forklift licence (LO an advantage)', 'Availability for a consistent afternoon shift', 'Steel-cap boots', 'Right to work in Australia']::text[])
on conflict (id) do nothing;
